# This is a basic workflow to help you get started with Actions

name: CI and deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure pnpm is available
        run: |
          if ! command -v pnpm &> /dev/null; then
            echo "❌ pnpm is not installed"
            exit 1
          else
            echo "✅ pnpm is installed"
          fi

  lint-build-deploy:
    needs: check-pnpm
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Clean install dependencies (CI)
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Build project
        run: pnpm build

      - name: Deploy to GitHub Pages
        run: pnpm deploy
